# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

read <- function(filepath) {
    .Call(`_c3dr_read`, filepath)
}

get_data <- function(filepath) {
    .Call(`_c3dr_get_data`, filepath)
}

get_analogs <- function(filepath) {
    .Call(`_c3dr_get_analogs`, filepath)
}

