#' Write data to a c3d object
#'
#' Set new data to an existing c3d object
#'
#' @param object A \code{c3d} object to be modified.
#' @param newdata The new point data that should be written to the \code{c3d}
#'   object. Usually a data frame of the class \code{c3d_data} as it is
#'   generated by \code{\link{c3d_data}}.
#' @param newanalog The new analog data that should be written to the \code{c3d}
#'   object. Usually a data frame of the class \code{c3d_analog} as it is
#'   generated by \code{\link{c3d_analog}}.
#'
#' @return The modified c3d object.
#'
#' @examples
#' # Import example data
#' d <- c3d_read(c3d_example())
#'
#' # remove last frame from point data and analog data (10 subframes for analog)
#' d_cut <- c3d_data(d)[-340,]
#' a_cut <- c3d_analog(d)[-c(3391:3400),]
#'
#' # write the new c3d object
#' d_new <- c3d_setdata(d, newdata = d_cut, newanalog = a_cut)
#' d_new
#'
#' @export

c3d_setdata <- function(object, newdata = NULL, newanalog = NULL) {

  # input validation
  if (!inherits(object, "c3d")) stop("'object' needs to be a list of class 'c3d'.")

  # set new point data
  if (!is.null(newdata)) {
    nd <- create_newdata(newdata)
    # rewrite point data
    object$data <- nd[["data"]]
    # rewrite point labels
    object$parameters$POINT$LABELS <- nd[["labels"]]
    object$labels <- nd[["labels"]]
    # rewrite number of points
    object$parameters$POINT$USED <- length(nd[["labels"]])
    object$header$npoints <- length(nd[["labels"]])
    # rewrite frame number
    object$parameters$POINT$FRAMES <- length(nd[["data"]])
    object$header$nframes <- length(nd[["data"]])
  }

  # set new analog data
  if (!is.null(newanalog)) {
    # get number of subframes
    n_subframes <- object$header$analogperframe
    na <- create_newanalog(newanalog, n_subframes)

    # rewrite analog data
    object$analog <- na[["data"]]
    # rewrite analog labels
    object$alabels <- na[["labels"]]
    object$parameters$ANALOG$LABELS <- na[["labels"]]
    # rewrite number of analog channels
    object$header$nanalogs <- length(na[["labels"]])
    object$parameters$ANALOG$USED <- length(na[["labels"]])

    # warning if analog data is incomplete for subframes
    if (nrow(newanalog) %% n_subframes != 0) {
      warning("Analog data length is not a multiplier of point data length.")
    }
  }

  # warnings if data is not exactly compatible
  if (length(object$data) < length(object$analog)) {
    warning("Point data has less frames than analog data.")
  } else if (length(object$data) > length(object$analog)) {
    warning("Analog data has less frames than point data. This may lead to corrupt c3d files.")
  }
  object
}

create_newdata <- function(newdata) {
  if (!inherits(newdata, "c3d_data")) stop("'newdata' needs to be a data.frame of class 'c3d_data'.")
  # convert to long data format if necessary
  frmt <- class(newdata)[1]
  if (frmt == "c3d_data_longest") {
    d = newdata # no conversion required
  } else if (frmt == "c3d_data_longer" | frmt == "c3d_data_wide") {
    d = c3d_longest(newdata)
  } else if (is.null(frmt)) {
    d = c3d_longest(newdata)
    message("assumed wide format")
  } else {
    stop("Unknown c3d_data format")
  }

  # write data to list format
  frames <- unique(d$frame)
  points <- unique(d$point)

  out <- vector("list", length(frames))

  # Split data by frames and points for faster access
  data_split <- split(d, list(d$frame, d$point), drop = TRUE)

  for (i in seq_along(frames)) {
    frame <- frames[i]
    frame_data <- data_split[grep(paste0("^", frame, "\\."), names(data_split))]

    out[[i]] <- lapply(points, function(point) {
      point_data <- frame_data[[paste0(frame, ".", point)]]
      if (!is.null(point_data)) {
        c(
          point_data$value[point_data$type == "x"],
          point_data$value[point_data$type == "y"],
          point_data$value[point_data$type == "z"]
        )
      } else {
        c(NA, NA, NA)
      }
    })
  }
  list(
    data = out,
    labels = points
  )
}

create_newanalog <- function(newanalog, nperframe) {
  if (!inherits(newanalog, "c3d_analog")) stop("'newanalog' needs to be a data.frame of class 'c3d_analog'.")
  # get frame id
  frame <- ceiling(seq_len(nrow(newanalog)) / nperframe)
  # Split data frame based on frames
  df_list <- split(newanalog, frame)
  # convert to list of matrices
  mlist <- lapply(df_list, function(sub_df) {
    mat <- as.matrix(sub_df)
    dimnames(mat) <- NULL
    mat
  })
  names(mlist) <- NULL
  out <- list(
    data = mlist,
    labels = colnames(newanalog)
  )
  out
}

